# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\sonuc.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import resources

class Ui_MainWindow(object):
        
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(550, 740)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.background = QtWidgets.QLabel(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(0, 0, 551, 741))
        self.background.setStyleSheet("background-image: url(:/background/background.jpg);")
        self.background.setText("")
        self.background.setObjectName("background")
        self.kutuphane_yazisi = QtWidgets.QLabel(self.centralwidget)
        self.kutuphane_yazisi.setGeometry(QtCore.QRect(90, 90, 401, 601))
        self.kutuphane_yazisi.setMinimumSize(QtCore.QSize(221, 31))
        self.kutuphane_yazisi.setStyleSheet("background-color: rgba(255, 255, 255, 80);")
        self.kutuphane_yazisi.setObjectName("kutuphane_yazisi")
        MainWindow.setCentralWidget(self.centralwidget)
        self.kutuphane_yazisi.setWordWrap(True)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        with open("sonuç.txt", "r") as f:
            data = f.read()
        data = data.replace(")", ") \n")
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("Sonuclar", "Sonuclar"))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.kutuphane_yazisi.setFont(font)
        self.kutuphane_yazisi.setStyleSheet("color: white;")
        self.kutuphane_yazisi.setText(data)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())